import streamlit as st
import pandas as pd
import os
from graph import app_graph
from config import Config

st.set_page_config(page_title="Dynamic Underwriter", page_icon="🏥", layout="wide")

st.title("🏥 Dynamic Life & Health Underwriter")
st.markdown("### Real-Time Risk Pricing with Human-in-the-Loop")

# Sidebar
with st.sidebar:
    st.header("⚙️ Configuration")
    
    # Provider Selection
    provider = st.selectbox("LLM Provider", ["Azure OpenAI", "AWS Bedrock", "Google Gemini"])
    
    creds = {}
    
    if provider == "Azure OpenAI":
        api_key = st.text_input("Azure OpenAI Key", type="password", help="Overrides Config")
        endpoint = st.text_input("Azure Endpoint", help="Overrides Config")
        if api_key: creds["azure_key"] = api_key
        if endpoint: creds["azure_endpoint"] = endpoint
        
    elif provider == "AWS Bedrock":
        creds["aws_access_key"] = st.text_input("AWS Access Key ID", type="password")
        creds["aws_secret_key"] = st.text_input("AWS Secret Access Key", type="password")
        creds["aws_region"] = st.text_input("AWS Region", value="us-east-1")
        creds["aws_model_id"] = st.text_input("Model ID", value="anthropic.claude-v2")
        
    elif provider == "Google Gemini":
        creds["google_key"] = st.text_input("Google API Key", type="password")
        creds["google_model"] = st.text_input("Model Name", value="gemini-pro")

    st.divider()

    st.header("New Application")
    user_id = st.selectbox("Select Applicant", ["user123", "user456"])
    
    if st.button("Start Underwriting", type="primary"):
        # Unique thread ID for persistence
        thread_id = f"case_{user_id}" 
        config = {"configurable": {"thread_id": thread_id}}
        
        initial_state = {
            "user_id": user_id,
            "provider": provider,
            "credentials": creds
        }
        
        # Start the graph (will pause at interrupt)
        with st.spinner("Ingesting IoT/EHR Data..."):
            app_graph.invoke(initial_state, config=config)
        st.success(f"Case {thread_id} Started & Paused for Review!")
        st.rerun()

# Main Dashboard: Review Queue
st.subheader("📋 Underwriter Review Queue")

# In a real app, we'd query the DB for all threads. 
# Here we simulate by letting user pick the thread to inspect.
active_case = st.selectbox("Inspect Case ID", ["case_user123", "case_user456"])
config = {"configurable": {"thread_id": active_case}}

# Get Current State from Persistence
try:
    current_state = app_graph.get_state(config)
except Exception:
    current_state = None

if current_state and current_state.values:
    state_data = current_state.values
    risk = state_data.get('risk_analysis')
    
    if risk:
        col1, col2 = st.columns([2, 1])
        
        with col1:
            st.info(f"**Applicant**: {state_data.get('user_id')}")
            
            # Medical History Display
            st.markdown("#### 🩺 Relevant Medical History")
            history_df = pd.DataFrame(risk['relevant_conditions'])
            st.dataframe(history_df, use_container_width=True)
            
            # Reasoning
            st.markdown("#### 🧠 Agent Reasoning")
            st.write(risk.get('reasoning', 'Reasoning generated by Logic Engine.'))
            
            # Suggestion
            st.markdown("#### 💡 Proposed Policy")
            st.write(f"**Premium**: ${risk['suggested_premium']}/month")
            st.write("**Nudges**:")
            for nudge in risk['nudges']:
                st.write(f"- {nudge}")

        with col2:
            st.markdown("### Decision")
            st.warning("⚠️ Workflow Paused: Waiting for Approval")
            
            with st.form("decision_form"):
                decision = st.radio("Underwriter Decision", ["Approve", "Reject"])
                submit = st.form_submit_button("Submit Decision")
                
                if submit:
                    # Resume the Graph
                    app_graph.update_state(config, {"human_decision": decision})
                    
                    with st.spinner("Finalizing Policy..."):
                        # None input resumes from the last state/update
                        for event in app_graph.stream(None, config=config):
                            pass
                    
                    st.success("Decision Processed!")
                    st.rerun()
                    
    elif state_data.get('final_policy'):
        st.success(f"Case Closed. Status: {state_data['final_policy']['status']}")
        st.json(state_data['final_policy'])
        
else:
    st.info("No active state found for this case. Start a new application in the sidebar.")
