# Azure APIM Terraform Config generated by AI-DDO
provider "azurerm" {
  features {}
}


resource "azurerm_api_management_api" "default" {
  name                = "default"
  resource_group_name = "my-resource-group"
  api_management_name = "my-apim-service"
  revision            = "1"
  display_name        = "default"
  path                = "default"
  protocols           = ["https"]
  service_url         = "https://httpbin.org/get"
}


resource "azurerm_api_management_api_operation" "default-login" {
  operation_id        = "default-login"
  api_name            = azurerm_api_management_api.default.name
  api_management_name = "my-apim-service"
  resource_group_name = "my-resource-group"
  display_name        = "Login"
  method              = "POST"
  url_template        = "/login"
  response {
    status = 200
  }
}


resource "azurerm_api_management_api_policy" "default-policy" {
  api_name            = azurerm_api_management_api.default.name
  api_management_name = "my-apim-service"
  resource_group_name = "my-resource-group"
  xml_content         = <<XML

<policies>
    <inbound>
        <base />
        <check-header name="x-api-key" failed-check-httpcode="401" failed-check-error-message="Unauthorized" ignore-case="true">
            <value>sample-key</value>
        </check-header>
    </inbound>
    <backend>
        <base />
    </backend>
    <outbound>
        <base />
    </outbound>
    <on-error>
        <base />
    </on-error>
</policies>
XML
}
